version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  mysql_data:
